{
 "title": "PariVision",
 "tags": [ "PariVision" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://parivision.heuzef.com\" target=\"_blank\" title=\"Go to  website\">\n<img width=\"400px\" alt=\"PariVision\" src=\"https://parivision.heuzef.com/assets/icons/logo.svg\">\n</a>\n<hr />\n<p><a href=\"https://parivision.heuzef.com\" target=\"_blank\" title=\"Go to  website\">https://parivision.heuzef.com</a></p>\n<p>Projet d'étude MLOPS de 2025, prediction des paris sportif autour du NBA.</p>\n<p>C’est un problème parfait pour traiter l’ensemble des étapes d’un projet de Data Science.</p>"
   }
  },
  {
   "title": "PRESSION",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 14, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "Containers en cours d'execution",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Utilisation du CPU par conteneurs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id,name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Utilisation de la mémoire par conteneurs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Service MongoDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"mongodb-exporter:9216\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rapport sur la dérive des données",
   "type": "table",
   "description": "Rapport complet",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "columns": [
      { "selector": "script", "text": "", "type": "string" }
     ],
     "parser": "simple",
     "root_selector": "head",
     "source": "url",
     "type": "html",
     "url": "http://parivision.heuzef.com:8000/Drift_Monitoring_Report.html",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Alertes Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Espace disque libre",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "{{mountpoint}} - Available" }
   ]
  },
  {
   "title": "Nombre de predictions effectuée",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inference_time_seconds_count{job=\"parivision_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps cumulés d'exécution des prédictions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "inference_time_seconds_sum{instance=\"parivision:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps de fonctionnement",
   "type": "stat",
   "description": "Uptime",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Cibles en lignes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Trafic réseau par paquets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "rate(node_network_transmit_packets_total[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  }
 ]
}