# Streamlit App
# Utiliser une image de base Python
FROM python:3.9-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de l'application
COPY .env .
COPY app .
COPY ../reports/WORKFLOW.png .

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

# Installer les dépendances
RUN pip3 install --no-cache-dir -r /app/requirements.txt

# Port
EXPOSE 8501

# Surveillance du service
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Commande par défaut pour démarrer l'application
ENTRYPOINT ["streamlit", "run", "Introduction.py", "--server.port=8501", "--server.address=0.0.0.0"]