version: "3.9"

services:
  
  virtualbetsapi:
    container_name: virtualbetsapi_container
    image: virtualbetsapi_image
    build:
      context: .
      dockerfile: Dockerfile_virtualbetsapi
    ports:
      - "8800:8800"
    networks:
      - parivision_net

networks:
  parivision_net:
    driver: bridge