# Utiliser une image de base Python
FROM python:3.9.11-alpine3.15

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de l'application
COPY virtualbetsapi/main.py /app/
COPY virtualbetsapi/requirements.txt /app/
COPY virtualbetsapi/data/data_nba.json /app/data/

# Installer les dépendances
RUN pip3 install --no-cache-dir -r /app/requirements.txt

# Port
EXPOSE 8800

# Commande par défaut pour démarrer l'application
CMD python3 -m uvicorn main:app --host 0.0.0.0 --port 8800